### ISSUE TITLE
[BUG] Injection failed on MyApp

### ISSUE THREAD

**Issue by sfc9982** [Yoshino-s/ElectronInjector#1]
我在对我自己开发的App进行测试时，并未成功

- 依赖安装好了，无报错。
- 环境为 **Windows**，没有权限问题
- Python **3.9.5 3.10.2** 均尝试过
- 直接在`app.asar.unpacked/` 里注入的。

```
pwsh> sudo python main.py -I ./inject/*****.js
Cannot find injection point in program file: main.node
```

我打开`main.node`发现没有可读的字符串，是不是换掉了？
`main.node` 在文末附上了

希望您有空的时候看看。谢谢！

[main.node.zip](https://github.com/Yoshino-s/ElectronInjector/files/8631550/main.node.zip)

**Comment by yoshino-s** [comment]
Fixed in ef335c2c5b7a4924eeb013b084646f8b1da096d0

**Comment by sfc9982** [comment]
> Fixed in ef335c2c5b7a4924eeb013b084646f8b1da096d0

Thanks
