### ISSUE TITLE
[BUG] SomeApp v1.3.6 is not working

### ISSUE THREAD

**Issue by Qynklee** [Yoshino-s/ElectronInjector#3]
Cant find valid injection point.

**Comment by yoshino-s** [comment]
FIxed in d8c96e6334d65584a2b69a7098abe95d35043dbd

**Comment by ZQhaha** [comment]
> FIxed in [d8c96e6](https://github.com/Yoshino-s/ElectronInjector/commit/d8c96e6334d65584a2b69a7098abe95d35043dbd)

请问有py版本么

**Comment by yoshino-s** [comment]
为了方便大家操作所以迁移到go了 :P
目前不打算继续使用python写了
